/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class WaylandIdleNotifier {
  constructor(timeoutMs: number)
  isIdle(): boolean
  on(notification: IdleNotification, callback: () => void): void
}

export declare const enum IdleNotification {
  Idled = 'Idled',
  Resumed = 'Resumed'
}
